import { locales } from '@/configs/i18n.config';
import { cn } from '@/utils/cn';
import '@/styles/global.css';
import type { LayoutType } from '@/types/component.types';
import type { Metadata } from 'next';
import { NextIntlClientProvider } from 'next-intl';
import { Footer, Header } from '@/layout';
import { routing } from '@/i18n/routing';
import { notFound } from 'next/navigation';

// TODO: Add metadata for the site
export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
	openGraph:{
		title: 'Enersok',
		type: 'website',
		url: 'https://example.com',
		description:'Enersok is a company that provides energy solutions for your home or business. We offer solar panels, battery storage, and electric vehicle charging stations to help you save money on your energy bills and reduce your carbon footprint.',
	},
	twitter:{
		card: 'summary_large_image',
	}
};

export const generateStaticParams = async () => {
	return locales.map((locale) => ({ locale }));
};

const RootLayout: LayoutType = async ({ children, params }) => {
	const { locale } = await params;
	if (!routing.locales.includes(locale)) {
		notFound();
	}

	return (
		<html
			lang={locale}
			className={cn('text-balance antialiased font-mori scroll-smooth')}
		>
			<head>
				<link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96" />
				<link rel="icon" type="image/svg+xml" href="/favicon.svg" />
				<link rel="shortcut icon" href="/favicon.ico" />
				<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
				<meta name="apple-mobile-web-app-title" content="Enersok" />
				<link rel="manifest" href="/site.webmanifest" />
			</head>
			<body>
				<NextIntlClientProvider>
					<Header locale={locale} />
					<main>{children}</main>
					<Footer />
				</NextIntlClientProvider>
			</body>
		</html>
	);
};

export default RootLayout;
