import { locales } from '@/configs/i18n.config';
import { cn } from '@/utils/cn';
import '@/styles/global.css';
import type { LayoutType } from '@/types/component.types';
import type { Metadata } from 'next';
import { Footer, Header } from '@/layout';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export const generateStaticParams = async () => {
	return locales.map((locale) => ({ locale }));
};

const RootLayout: LayoutType = async ({
	children,
	params: { locale },
}) => {

	return (
		<html
			lang={locale}
			className={cn('text-balance antialiased font-mori')}
		>
			<body>
				<Header
					locale={locale}
				/>
				{children}
				<Footer />
			</body>
		</html>
	);
};

export default RootLayout;
