import { locales } from '@/configs/i18n.config';
import { cn } from '@/utils/cn';
import '@/styles/global.css';
import type { LayoutType } from '@/types/component.types';
import type { Metadata } from 'next';
import { NextIntlClientProvider } from 'next-intl';
import { setRequestLocale } from 'next-intl/server';
import { Footer, Header } from '@/layout';
import { routing } from '@/i18n/routing';
import { notFound } from 'next/navigation';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export const generateStaticParams = async () => {
	return locales.map((locale) => ({ locale }));
};

const RootLayout: LayoutType = async ({
	children,
	params,
}) => {

	const { locale } = await params;
	if (!routing.locales.includes(locale)) {
		notFound();
	}

	setRequestLocale(locale);

	return (
		<html
			lang={locale}
			className={cn('text-balance antialiased font-mori scroll-smooth')}
		>
			<body>
				<NextIntlClientProvider>
					<Header
						locale={locale}
					/>
					<main>
						{children}
					</main>
					<Footer />
				</NextIntlClientProvider>
			</body>
		</html>
	);
};

export default RootLayout;
